--  Configuration for esp32_c3_wifi generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Esp32_C3_Wifi_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0-dev";
   Crate_Name : constant String := "esp32_c3_wifi";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "homebrew";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Esp32_C3_Wifi_Config;
