name = "fvp_armv8r_aarch32_hello"
description = "Hello world app for ARM FVP ARMV8R platform"
version = "0.1.0-dev"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

executables = ["fvp_armv8r_aarch32_hello"]

[[depends-on]]
hirtos = "*"
#???porting_layer = "*"
portable_minimal_ada_rts = "*"

[[pins]]
hirtos = { path='../..' }
#???porting_layer = { path='../../porting_layer' }
portable_minimal_ada_rts = { path='../../third_party/portable_minimal_ada_rts' }

[build-profiles]
hirtos = "development"
#???porting_layer = "development"
portable_minimal_ada_rts = "development"
