name = "fvp_armv8r_aarch32_hello"
description = "Hello world app for ARM FVP ARMV8R platform"
version = "0.1.0-dev"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

executables = ["fvp_armv8r_aarch32_hello"]

[[depends-on]]
hirtos = "*"
gnat_arm_elf = "*"
gnatprove = "*"

[[pins]]
hirtos = { path='../..' }

[gpr-set-externals]
CPU_Core = "arm_cortex_r52"

[build-profiles]
hirtos = "development"

[[actions]]
type = "post-build"
command = ["sh", "-c", "arm-none-eabi-objdump -dSstl bin/fvp_armv8r_aarch32_hello.elf > bin/fvp_armv8r_aarch32_hello.lst"]


