#
# Copyright (c) 2022-2024, German Rivera
#
# SPDX-License-Identifier: Apache-2.0
#
name = "hirtos"
description = "High-Integrity RTOS"
version = "2.0.0"
licenses = "Apache-2.0"
website = "https://github.com/jgrivera67/HiRTOS"
tags = ["rtos"]
authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

[configuration.variables]
Platform = {type = "Enum", values = ["arm_fvp", "esp32_c3"], default = "arm_fvp"}

[[depends-on]]
gnat = "^13.2.1"
gnatprove = "^13.2.1"

[[actions]]
type = "test"
command = ["alr", "build"]
directory = "sample_apps/fvp_armv8r_aarch32_hello"

[[actions]]
type = "test"
command = ["alr", "build"]
directory = "sample_apps/esp32_c3_hello"
