name = "hello_partition1"
description = "Hello partition1"
version = "0.1.0-dev"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

executables = ["hello_partition1"]

[[depends-on]]
hirtos = "*"
gnat_arm_elf = "*"

[[pins]]
hirtos = { path='../../..' }

[gpr-set-externals]
CPU_Core = "arm_cortex_r52"

[build-profiles]
hirtos = "development"

[[actions]]
type = "post-build"
command = ["arm-eabi-objcopy", "-O", "binary", "-S", "bin/hello_partition1.elf",
           "bin/hello_partition1.bin"]

[[actions]]
type = "post-build"
command = ["sh", "-c", "arm-eabi-objdump -dSstl bin/hello_partition1.elf > bin/hello_partition1.lst"]

