#
# NOTE: Before building for the first time with `alr build`, select the
# corresponding cross compiler toolchain by running `alr toolchain --select`
#
name = "hirtos_separation_kernel"
description = "High-Integrity RTOS Separation Kernel"
version = "1.0.0"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

[[depends-on]]
gnatprove = "^12.1.1"
portable_minimal_ada_rts = "1.0.0"

