/* Configuration for hirtos generated by Alire */
#ifndef HIRTOS_CONFIG_H
#define HIRTOS_CONFIG_H

#define CRATE_VERSION "2.0.0"
#define CRATE_NAME "hirtos"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#define PLATFORM_ARM_FVP 1
#define PLATFORM_ESP32_C3 2
#define PLATFORM_ESP32_P4 3
#define PLATFORM_RASPBERRY_PI4 4
#define PLATFORM_RASPBERRY_PI5 5

#define PLATFORM  5

#endif
