/* Configuration for hirtos generated by Alire */
#ifndef HIRTOS_CONFIG_H
#define HIRTOS_CONFIG_H

#define CRATE_VERSION "0.0.0"
#define CRATE_NAME "hirtos"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "distro_unknown"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
