/* Configuration for nxp_kl25z_hello generated by Alire */
#ifndef NXP_KL25Z_HELLO_CONFIG_H
#define NXP_KL25Z_HELLO_CONFIG_H

#define CRATE_VERSION "0.1.0-dev"
#define CRATE_NAME "nxp_kl25z_hello"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
