--
--  Copyright (c) 2022-2025, German Rivera
--
--
--  SPDX-License-Identifier: Apache-2.0
--

with HiRTOS_Cpu_Arch_Interface.System_Registers;
with HiRTOS_Platform_Parameters;
with Memory_Utils;
with System.Machine_Code;
with System.Storage_Elements;

package body HiRTOS_Cpu_Startup_Interface is
   use HiRTOS_Cpu_Arch_Interface.System_Registers;
   use HiRTOS_Cpu_Multi_Core_Interface;
   use System.Storage_Elements;
   use ASCII;

   ----------------
   -- Enable_FPU --
   ----------------

   procedure Enable_FPU is
      CPACR_Value : CPACR_EL1_Type;
   begin
      --
      --  Enable full access to FPU
      --
      CPACR_Value := Get_CPACR_EL1;
      CPACR_Value.FPEN := Advanced_SIMD_And_Floating_Point_Enabled_For_EL0_EL1;
      Set_CPACR_EL1 (CPACR_Value);

      System.Machine_Code.Asm (
         --
         --  Initializes floating-point registers:
         --
         "fmov d0, xzr" & LF &
         "fmov v0.d[1], xzr" & LF &
         "fmov d1, xzr" & LF &
         "fmov v1.d[1], xzr" & LF &
         "fmov d2, xzr" & LF &
         "fmov v2.d[1], xzr" & LF &
         "fmov d3, xzr" & LF &
         "fmov v3.d[1], xzr" & LF &
         "fmov d4, xzr" & LF &
         "fmov v4.d[1], xzr" & LF &
         "fmov d5, xzr" & LF &
         "fmov v5.d[1], xzr" & LF &
         "fmov d6, xzr" & LF &
         "fmov v6.d[1], xzr" & LF &
         "fmov d7, xzr" & LF &
         "fmov v7.d[1], xzr" & LF &
         "fmov d8, xzr" & LF &
         "fmov v8.d[1], xzr" & LF &
         "fmov d9, xzr" & LF &
         "fmov v9.d[1], xzr" & LF &
         "fmov d10, xzr" & LF &
         "fmov v10.d[1], xzr" & LF &
         "fmov d11, xzr" & LF &
         "fmov v11.d[1], xzr" & LF &
         "fmov d12, xzr" & LF &
         "fmov v12.d[1], xzr" & LF &
         "fmov d13, xzr" & LF &
         "fmov v13.d[1], xzr" & LF &
         "fmov d14, xzr" & LF &
         "fmov v14.d[1], xzr" & LF &
         "fmov d15, xzr" & LF &
         "fmov v15.d[1], xzr" & LF &
         "fmov d16, xzr" & LF &
         "fmov v16.d[1], xzr" & LF &
         "fmov d17, xzr" & LF &
         "fmov v17.d[1], xzr" & LF &
         "fmov d18, xzr" & LF &
         "fmov v18.d[1], xzr" & LF &
         "fmov d19, xzr" & LF &
         "fmov v19.d[1], xzr" & LF &
         "fmov d20, xzr" & LF &
         "fmov v20.d[1], xzr" & LF &
         "fmov d21, xzr" & LF &
         "fmov v21.d[1], xzr" & LF &
         "fmov d22, xzr" & LF &
         "fmov v22.d[1], xzr" & LF &
         "fmov d23, xzr" & LF &
         "fmov v23.d[1], xzr" & LF &
         "fmov d24, xzr" & LF &
         "fmov v24.d[1], xzr" & LF &
         "fmov d25, xzr" & LF &
         "fmov v25.d[1], xzr" & LF &
         "fmov d26, xzr" & LF &
         "fmov v26.d[1], xzr" & LF &
         "fmov d27, xzr" & LF &
         "fmov v27.d[1], xzr" & LF &
         "fmov d28, xzr" & LF &
         "fmov v28.d[1], xzr" & LF &
         "fmov d29, xzr" & LF &
         "fmov v29.d[1], xzr" & LF &
         "fmov d30, xzr" & LF &
         "fmov v30.d[1], xzr" & LF &
         "fmov d31, xzr" & LF &
         "fmov v31.d[1], xzr" & LF &
         "msr fpsr, xzr",
         Volatile => True);
   end Enable_FPU;

   -----------------------
   -- Ada_Reset_Handler --
   -----------------------

   procedure Ada_Reset_Handler is

      procedure Gnat_Generated_Main with Import,
                                         Convention => C,
                                         External_Name => "main",
                                         No_Return;

      procedure App_Main with Import,
                              Convention => Ada,
                              External_Name => "_ada_app_main",
                              No_Return;

      Global_Data_Region_Size_In_Bytes : constant Integer_Address :=
         To_Integer (HiRTOS_Platform_Parameters.Global_Data_Region_End_Address) -
         To_Integer (HiRTOS_Platform_Parameters.Global_Data_Region_Start_Address);
   begin
      --  This does not work on ARM FVP:
      --??? HiRTOS_Cpu_Arch_Interface.Enable_Caches;
      Enable_FPU;

      if Get_Cpu_Id = Valid_Cpu_Core_Id_Type'First then
         --
         --  In case C code is invoked from Ada, C global variables
         --  need to be initialized in RAM:
         --
         Memory_Utils.Copy_Data_Section;
         Memory_Utils.Clear_BSS_Section;
         Memory_Utils.Clear_Privileged_BSS_Section;
         Memory_Utils.Flush_Data_Cache_Range (
            HiRTOS_Platform_Parameters.Global_Data_Region_Start_Address,
            Global_Data_Region_Size_In_Bytes);

         --
         --  Call main() generated by gnat binder, which will do the elaboration
         --  of Ada library-level packages and then invoke the main Ada subprogram
         --
         --  NOTE: Before calling 'Gnat_Generated_Main' only
         --  "No_Elaboration_Code_All" packages can be invoked.
         --
         Gnat_Generated_Main;
      else
         --
         --  For secondary cores, just call the application's main, to avoid doing
         --  elaboration of application packages more than once.
         --
         App_Main;
      end if;

      --
      --  We should not return here
      --
      pragma Warnings (Off, "unreachable code");
      loop
         HiRTOS_Cpu_Arch_Interface.Wait_For_Interrupt;
      end loop;
   end Ada_Reset_Handler;

end HiRTOS_Cpu_Startup_Interface;
