/* Configuration for hirtos_separation_kernel generated by Alire */
#ifndef HIRTOS_SEPARATION_KERNEL_CONFIG_H
#define HIRTOS_SEPARATION_KERNEL_CONFIG_H

#define CRATE_VERSION "0.0.0"
#define CRATE_NAME "hirtos_separation_kernel"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
