--
--  Copyright (c) 2022-2023, German Rivera
--
--
--  SPDX-License-Identifier: Apache-2.0
--

with HiRTOS_Platform_Parameters;
with Memory_Utils;
with Watchdog_Driver;
with System.Storage_Elements;

package body HiRTOS_Cpu_Startup_Interface is
   use HiRTOS_Cpu_Multi_Core_Interface;
   use System.Storage_Elements;

   -----------------------
   -- Ada_Reset_Handler --
   -----------------------

   procedure Ada_Reset_Handler is

      procedure Gnat_Generated_Main with Import,
                                         Convention => C,
                                         External_Name => "main",
                                         No_Return;

      procedure App_Main with Import,
                              Convention => Ada,
                              External_Name => "_ada_app_main",
                              No_Return;

      Global_Data_Region_Size_In_Bytes : constant Integer_Address :=
         To_Integer (HiRTOS_Platform_Parameters.Global_Data_Region_End_Address) -
         To_Integer (HiRTOS_Platform_Parameters.Global_Data_Region_Start_Address);

   begin
      pragma Warnings (Off, "condition can only be False if invalid values present");
      if Get_Cpu_Id = Valid_Cpu_Core_Id_Type'First then
         --
         --  Watchdog timer needs to disabled as soon as possible, to prevent
         --  it from firing, in case it is enabled by default:
         --
         Watchdog_Driver.Initialize;

         --
         --  In case C code is invoked from Ada, C global variables
         --  need to be initialized in RAM:
         --
         Memory_Utils.Copy_Data_Section;
         Memory_Utils.Clear_BSS_Section;
         Memory_Utils.Clear_Privileged_BSS_Section;
         Memory_Utils.Flush_Data_Cache_Range (
            HiRTOS_Platform_Parameters.Global_Data_Region_Start_Address,
            Global_Data_Region_Size_In_Bytes);

         --
         --  Call main() generated by gnat binder, which will do the elaboration
         --  of Ada library-level packages and then invoke the main Ada subprogram
         --
         --  NOTE: Before calling 'Gnat_Generated_Main' only
         --  "No_Elaboration_Code_All" packages can be invoked.
         --
         Gnat_Generated_Main;
      else
         --
         --  For secondary cores, just call the application's main, to avoid doing
         --  elaboration of application packages more than once.
         --
         App_Main;
      end if;
      pragma Warnings (On, "condition can only be False if invalid values present");

      --
      --  We should not return here
      --
      pragma Warnings (Off, "unreachable code");
      loop
         HiRTOS_Cpu_Arch_Interface.Wait_For_Interrupt;
      end loop;
   end Ada_Reset_Handler;

end HiRTOS_Cpu_Startup_Interface;
