name = "hello_partition2"
description = "Hello partition2"
version = "0.1.0-dev"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]

executables = ["hello_partition2"]

[[depends-on]]
hirtos = "*"
gnat_arm_elf = "^13.2.1"

[[pins]]
hirtos = { path='../../..' }

[gpr-set-externals]
CPU_Core = "arm_cortex_r52"

[build-profiles]
hirtos = "development"

[[actions]]
type = "post-build"
command = ["arm-none-eabi-objcopy", "-O", "binary", "-S", "bin/hello_partition2.elf",
           "bin/hello_partition2.bin"]

[[actions]]
type = "post-build"
command = ["sh", "-c", "arm-none-eabi-objdump -dSstl bin/hello_partition2.elf > bin/hello_partition2.lst"]

