name = "common_foundation"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["J. German Rivera"]
maintainers = ["J. German Rivera <jgrivera67@gmail.com>"]
maintainers-logins = ["jgrivera67"]
[[depends-on]]
#hirtos = "*"
portable_minimal_ada_rts = "*"

[[pins]]
#hirtos = { path='../..' }
portable_minimal_ada_rts = { path='../../third_party/portable_minimal_ada_rts' }

[build-profiles]
#hirtos = "development"
portable_minimal_ada_rts = "development"